### PR TITLE
Merge sort.java

### PR DESCRIPTION
**Pull request by divya1509**
Merge sort Algo in java

### CODE REVIEW

**Comment by Kevinpaulose05** [comment]
Pls open an issue first. I will assign it to you and then contribute. Also please try to do a contribution like [this](https://github.com/divya1509/DSA/tree/patch-1/Array%20in%20Javascript) as a microbyte.  Also give PR description like [this](https://github.com/Crio-Bytes/Miscellaneous/pull/1). Please follow a formal workflow for correct recognition.

**Comment by divya1509** [comment]
ok thanks

**Comment by Kevinpaulose05** [comment]
I see there are no changes that have happened since then. if you have any queries or problems pls share. We can sort it out. 

Cheers

**Comment by divya1509** [comment]
I have opened a new pull request.

**Pull request closed without merging**
