### PR TITLE
Fixes Issue #23

### LINKED ISSUE #23: Add traverse and update activites for Array in Javascript MicroByte
**MicroByte Title:** Array in Javascript

**Improvement Proposal:** <list out what improvements you are proposing to provide>

- Adding an activity for traversing the array, both forward and backwards
- Adding an activity for updating the array, at various indices or as a whole

**Benefits of proposed improvements:** <list out the benefits of the aforementioned improvements you want to offer>

- Would be more beginner friendly for student developers who're looking forward to learn JavaScript

### PR DESCRIPTION
**Pull request by Janhavi-Gautam**
# Closes #23

Added a MicroByte to involve learners to learn features of Traversing and Updating array in JavaScript.
Checklist:
- [x] Added/updated activities for learners
- [x] Didn't give the solutions to the added/updated activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well-documented code (if source code files are involved)

### CODE REVIEW

**Comment by Janhavi-Gautam** [comment]
This is complete code for Updating feature.
Please check.

**Comment by Ak-Shaw** [comment]
@Janhavi-Gautam It seems like you are not a @CrioDo #IBelieveinDoing Hacktoberfest participant. Are you? If not kindly register yourself using [this](https://www.crio.do/IBelieveInDoing/October/?utm_source=adv&name=AyushShaw) link.

Plus, your work is under review.

**Comment by Kevinpaulose05** [comment]
> @Janhavi-Gautam It seems like you are not a @CrioDo #IBelieveinDoing Hacktoberfest participant. Are you? If not kindly register yourself using [this](https://www.crio.do/IBelieveInDoing/October/?utm_source=adv&name=AyushShaw) link.
> 
> Plus, your work is under review.

@Janhavi-Gautam  Do this ASAP. 

Can u share the full code you are using here?
Ping me on [slack](https://criodo-world.slack.com/archives/D0179PV7WDQ) or mail me [at](kevinpaulose35@gmail.com)

**Comment by Janhavi-Gautam** [comment]
> > @Janhavi-Gautam It seems like you are not a @CrioDo #IBelieveinDoing Hacktoberfest participant. Are you? If not kindly register yourself using [this](https://www.crio.do/IBelieveInDoing/October/?utm_source=adv&name=AyushShaw) link.
> > Plus, your work is under review.
> 
> @Janhavi-Gautam Do this ASAP.
> 
> Can u share the full code you are using here?
> Ping me on slack or mail me [at](mailto:kevinpaulose35@gmail.com)

I have Mailed you Source Code for both the features , Kindly review it.

**Review by Kevinpaulose05 — CHANGES_REQUESTED** [review]
I reviewed ur code. One typo - color.indexOf('orange'); // returns 0 -------> U have 1 in ur code. Rest all is fine.
More important thing to do is edit ur PR description like [this](https://github.com/Janhavi-Gautam/DSA/blob/Janhavi-Gautam-patch-1-1/.github/PULL_REQUEST_TEMPLATE/updating-microbyte.md). Pls refer to other closed issues for reference.

**Review by Kevinpaulose05 — APPROVED** [review]
Good work. Try to solve more issues that are listed and are unassigned. U may open some of ur own. If u want u can be a creator by contributing ur own microbyte. Anyways nice work

**Comment by Ak-Shaw** [comment]
@all-contributors kindly add @Janhavi-Gautam for code

**Pull request merged**
