### PR TITLE
Implement Kadane's Algorithm

### PR DESCRIPTION
**Pull request by G1Joshi**
Kadane’s Algorithm for Maximum Sub-Array Sum.

### CODE REVIEW

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey can you add a section that defines:
1) Problem statement of Kadane's Algorithm
2) Why does it work?
You have already covered working of it 
3) Learners might be ones who don't know how to run it, so add instructions of how to compile and stuff in the Readme

**Review by Ak-Shaw — CHANGES_REQUESTED** [review]
Hey @G1Joshi ! The thing is that we are believers of the Crio motto of **#learnbydoing**, and so we need the MicroBytes to be along the same lines, that it needs to have activities that the user/learner can undergo to learn something. You can add at least a single activity in the _README.md_ and also make necessary changes to your code, if needed for the same. **_The main point is that it doesn't have to be a simple solution which anyone could've googled._** I hope you get the right direction of flow and do the needful.

**Comment by Kevinpaulose05** [comment]
Pls make sure u do the necessary changes as issues @G1Joshi . Only after that we will be merging it.
Cheers

**Comment by Kevinpaulose05** [comment]
@G1Joshi can u work on your microbyte a bit more. We expect you to submit something similar to [this](https://github.com/Crio-Bytes/DSA/tree/main/Array%20in%20Javascript) and [this](https://github.com/Crio-Bytes/DSA/tree/main/BinaryTree_LevelOrderTraversal_Types).  Pls work on it so that we can get your name up on the leaderboard ASAP :)

**Comment by G1Joshi** [comment]
I am working on this issue and soon I'll commit changes to this pull request.

**Comment by Ak-Shaw** [comment]
Cool. We're waiting for your contributions.

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @G1Joshi!
I see a large improvement over the previous versions and I personally like the efficiency comparison part.
However, I would request you to do the changes as follows:

1. It would be great if you could add some references too for the learners to pick and read.
2. You can add a few activities and questions. (For eg: Will this work if there are negative elements in the array, Will it work if there are duplicates etc) This will keep the MB slightly more engaging.
3. Try to think of some learner issues that can be raised over this one. (For eg: Return the maximum subarray's array too XP)

Otherwise, great improvement man. Kindly make these changes and we shall re review it asap 😄

**Review by Kevinpaulose05 — CHANGES_REQUESTED** [review]
The content u have currently is fine. But pls follow the structure of the readme like background,introduction, pre-requisites and then activities(refer other microbytes in miscallanoues section). Also u shud hide ur code. Give small hints which can facilitate learners to contribute to ur microbyte by giving out solutions for them. Or u can provide the code in the src and hints inn readme. In any way don't give out direct code(of the main part). 
All these changes will take just another half hour but will tremendously improve ur microbyte. Ur main purpose in the ned should be to make  ur microbyte as busy and engaging as possible for ppl who try out ur microbyte.
Kindly make these changes. I agree we  have been on this for too long but doing this will help us wrap up another quality microbyte. Hope u understand,

**Review by Kevinpaulose05 — APPROVED** [review]
Awesome work. Just a couple of things more:

1. Give a small mention of pre-requisites, like basic knowledge of C++ and time complexity
2.if possible give some article link to the applications(optional)

Another advocate will be reviewing and approving in some time. We will then merge your microbyte.

2 things to be done **only after merging**:
1. Open issues for learners(if the sope of contribution exists for ur microbyte)
2. Showcase ur microbyte in slack microbyte showcase channel in [this](https://github.com/Crio-Bytes/Demo-Repo/blob/master/Maintainer%20Resources/new-microbyte-showcase-template.md) way

Kudos to ur work and cooperation. 

Keep Contributing!!

**Review by archithdwij — APPROVED** [review]

**Review by sudhanshutiwari264 — APPROVED** [review]
looks Good to me!
Keep contributing!

**Comment by archithdwij** [comment]
@all-contributors kindly add @G1Joshi  for:

- [x] code
- [x] content
- [x] ideas
- [x] doc

**Pull request merged**
