### PR TITLE
Connect Nodes at same level

### PR DESCRIPTION
**Pull request by DivyaSaravanan**
#Issue Number 25
Have Added the code to connect Nodes at same Level in Cpp.(Solution using Level OrderTraversal )

### CODE REVIEW

**Comment by Ak-Shaw** [comment]
image
Your current code **contains quite a few compilation errors**. Kindly get them resolved.

**Comment by Ak-Shaw** [comment]
Also kindly use [this](https://github.com/Crio-Bytes/DSA/blob/main/.github/PULL_REQUEST_TEMPLATE/updating-microbyte.md) template for the description of a PR that updates a MicroByte. Basically edit the description of this PR to match the template.

**Review by Ak-Shaw — CHANGES_REQUESTED** [review]
Kindly do the needful.

**Comment by DivyaSaravanan** [comment]
Sorry for the inconvenience. Will do to appropriate changes @Ak-Shaw

**Comment by Ak-Shaw** [comment]
@DivyaSaravanan There's nothing called inconvenience in OSS. We're all here to help. :+1:

**Comment by DivyaSaravanan** [comment]
> @DivyaSaravanan There's nothing called inconvenience in OSS. We're all here to learn and grow.

:)

**Comment by DivyaSaravanan** [comment]
Have Updated ?! PR #32  Do check @Ak-Shaw

**Pull request closed without merging**
