### PR TITLE
Starter micro-byte

### PR DESCRIPTION
**Pull request by Kevinpaulose05**
The byte that everyone can and should start with for DSA contributions

### CODE REVIEW

**Review by Ak-Shaw — CHANGES_REQUESTED** [review]
We don't need a _CONTRIBUTING.md_ and _LICENCE_ in sub folders for the MicroBytes. Kindly remove them. All else seems fine and good to go with. Another request will be to give a proper name to the MicroByte. _Starter micro-byte_ seems kinda irrelavant.

**Review by Ak-Shaw — CHANGES_REQUESTED** [review]
@Kevinpaulose05 _We need all of your MicroByte files and folders in a folder, which is of the name of the MicroByte. That folder will be a sub-folder in the master repo of DSA._

**Comment by Kevinpaulose05** [comment]
i am making a fresh one. I have messed up my flow with this. Sry for the mess

**Comment by Ak-Shaw** [comment]
@Kevinpaulose05 You could've just committed the new changes in this PR you know. :sweat_smile: That way all the conversations are in one place and others can view the whole convo we're having, so that they understand it.

**Comment by Kevinpaulose05** [comment]
Oh. My bad. I will keep this in mind 🙂

**Pull request closed without merging**
