### PR TITLE
 Added Maximum element at a given Level in a Binary Tree

### LINKED ISSUE #27: How to find the maximum node at a given level in a binary tree
**MicroByte Title:** BinaryTree_LevelOrderTraversal_Types

**Improvement Proposal:** 
- Add solution to finding maximum node at a given level in a binary tree as mentioned in Further Exploration Question 4
- Implement it in any language and add briefly documented code

**Benefits of proposed improvements:** 

- The learner will be able to find a solution to the Further Exploration section too

### PR DESCRIPTION
**Pull request by DivyaSaravanan**
## Closes #27 

**Checklist:**
- [ ] Added/updated activities for learners
- [ ]  Didn't give the solutions to the added/updated activities straight away
- [ ] Followed a LearnByDoing approach
- [x]  Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by Ak-Shaw — CHANGES_REQUESTED** [review]
@DivyaSaravanan The code is fine. Just one tiny request though.

Line no. 119:
`cout << "Max Node in a Binary Tree of a given Level  is \n";`

Kindly change it a little, something like this would be nice:
`cout << "Max Node at level " << level << ": ";`

**Comment by Ak-Shaw** [comment]
Also I edited the checklist in the PR description, kept only the one's that you covered.

**Comment by DivyaSaravanan** [comment]
Okay will do it @Ak-Shaw

**Review by Ak-Shaw — APPROVED** [review]
LGTM now! :rocket: 

Piece of advice, always try to work on a separate branch other than main or master. This ensures a proper and easily maintainable workflow.

Nevertheless, one more positive approval shall lead to a merge. You are free to work on some other issues or go more adventurous by creating your own!

**Comment by DivyaSaravanan** [comment]
> LGTM now! 
> 
> Piece of advice, always try to work on a separate branch other than main or master. This ensures a proper and easily maintainable workflow.
> 
> Nevertheless, one more positive approval shall lead to a merge. You are free to work on some other issues or go more adventurous by creating your own!

Sure ! :) WIll follow in future work .

**Comment by DivyaSaravanan** [comment]
Can you elaborate on the first three checklists ? @Ak-Shaw

**Comment by Ak-Shaw** [comment]
@DivyaSaravanan Actually, we appreciate and recognize contributors based on the work they've done. You've provided a solution code and a image, so the checkmarks should imply your contributions solely. I hope that clears it.

**Review by sudhanshutiwari264 — APPROVED** [review]
LGTM !✨
keep contributing @divyanshrastogi51 !
Nice work !

**Comment by archithdwij** [comment]
@all-contributors kindly add @DivyaSaravanan for:

- [x] code
- [x] content

**Comment by DivyaSaravanan** [comment]
> @DivyaSaravanan Actually, we appreciate and recognize contributors based on the work they've done. You've provided a solution code and an image, so the checkmarks should imply your contributions solely. I hope that clears it.

Yeah ! Got it @Ak-Shaw ! :)

**Pull request merged**
