### PR TITLE
Added Level Order Traversal of a Binary Tree and different kinds of problems based on it

### PR DESCRIPTION
**Pull request by Anjalikamath**
Please let me know if any changes are required.

### CODE REVIEW

**Review by sudhanshutiwari264 — APPROVED** [review]
Great structure followed and nice content !

**Review by amoghrajesh — APPROVED** [review]
Good job @Anjalikamath 🥇

**Comment by Kevinpaulose05** [comment]
Nicely done @Anjalikamath . Liked ur structure and also good to see you are following the motto of crio.
Next thing that you should do is showcase this PR on microbyte-showcase channel.

Kindly follow the below mentioned format for ur msg @Anjalikamath -

All creators who have their PRs accepted and merged can show off their contribution in the microbyte-showcase channel. This will help the other participants by keeping them updated. Also, kindly refrain from spamming the channel with every minor contribution you may make. Please give a brief compiled overview of your contribution.

**Template** (Kindly stick to this format):
Title of your project #(repo-topic)
A brief overview of your project (not more than 3-5 lines). GITHUB LINK of byte must be provided. In the end of this briefing use #(languages), #(software), #(skills) tags.
Actively looking for contributors (both learners and creators). Please raise an issue first and then submit your PRs to that issue only (either after or before assigning the issue to you). Also, you can suggest how they can contribute.

**Template example:**
Concurrency #OS
Brief description. [GITHUB LINK]. #C++ #Python #Shell #Django
Actively looking for contributors. Learners can to this _ and creators can do this __. **Please raise an issue first and then submit your PRs to that issue only.**
#learnbydoing #microbyte-showcase

Needless to say keep contributing!!

**Comment by Anjalikamath** [comment]
@sudhanshutiwari264  @amoghrajesh  Thank You!

**Comment by Anjalikamath** [comment]
@Kevinpaulose05  Thanks a lot! I have also showcased my PR on the microbyte-showcase channel .

**Comment by Ak-Shaw** [comment]
@all-contributors kindly add @Anjalikamath  for code doc ideas content

**Comment by Ak-Shaw** [comment]
@all-contributors kindly add @sudhanshutiwari264 for review and eventOrganizing

**Pull request merged**
