### PR TITLE
First look of DSA 

### PR DESCRIPTION
**Pull request by Kevinpaulose05**
I may have derailed from the main layout needed to be followed. please let me know what is to be rectified if any is needed.

### CODE REVIEW

**Comment by Ak-Shaw** [comment]
@Kevinpaulose05 Kindly follow the folder structure from next time. The repos need to be treated as master repos, which contain folders for various MicroBytes, and your content has to go under one such folder. _If you further doubts, feel free to ask_.

**Comment by Kevinpaulose05** [comment]
I could not think of how to could create microbytes for DSA. Each algorithm/DS is independent in itself. The only thing that can be done is variety of languages. That's y i made it this way. If u have any suggestions for folder structure pls share

**Comment by Ak-Shaw** [comment]
image
I hope this helps.

**Comment by Ak-Shaw** [comment]
You can refer [this](https://github.com/Crio-Bytes/Function_Call_Stack-Reference) for folder structure.

**Comment by Kevinpaulose05** [comment]
> You can refer [this](https://github.com/Crio-Bytes/Function_Call_Stack-Reference) for folder structure.

But for DSA i don't think it is fine to go with that one. Let me take this one up with Som sir. He can let me know what he ahs on his mind

**Comment by Kevinpaulose05** [comment]
Also is there anyone else working on DSA?

**Comment by Ak-Shaw** [comment]
> But for DSA i don't think it is fine to go with that one. Let me take this one up with Som sir. He can let me know what he ahs on his mind

Yeah, go for it.



> Also is there anyone else working on DSA?

Dunno.

**Pull request closed without merging**
