### PR TITLE
Micro-Byte on Array

### PR DESCRIPTION
**Pull request by divyanshrastogi51**
This PR Solve #10

### CODE REVIEW

**Review by Kevinpaulose05 — COMMENTED** [review]
Nicely done @divyanshrastogi51 . Just a few things u can add to complete this PR.

1. Put a couple of code examples in a folder named 'src' within ur microbyte.
2. Open an issue with this topic in Getting Started with DSA microbyte and make this PR there too in the correct folder.
 
Microbyte structure is pretty good(only 'src' is missin)!
Maybe next time you an pick better topics. Arrays are very basic. U can combine multiple easy concepts too.

**Review by Kevinpaulose05 — APPROVED** [review]
Next time try picking a mixed or tougher concept than this. For first PR this is fine.

**Comment by divyanshrastogi51** [comment]
Ya sure. but I did not understand the 2nd point. I have mentioned the issue

**Comment by Kevinpaulose05** [comment]
Nicely done @divyanshrastogi51 . Just a few things u can add to complete it

> Ya sure. but I did not understand the 2nd point. I have mentioned the issue

What i mean is u can simply contribute to that microbyte so that Getting Started with DSA will have more DSA to its collection and also u will get a PR

**Review by codehack31 — APPROVED** [review]
Good structure maintenance @divyanshrastogi51 . Your content is well - detailed. Good job! looking forward for more contributions.

**Comment by Kevinpaulose05** [comment]
Pls mention the files in ur src folder in the readme so that ppl will know what exits in src.

**Comment by Ak-Shaw** [comment]
> Ya sure. but I did not understand the 2nd point. I have mentioned the issue

Kindly refer [this](https://github.com/Crio-Bytes/Miscellaneous/pull/1#issuecomment-711235458) for PR description template. 

Coming to the content. LGTM! We'll merge it once you update the PR description with proper template.

**Comment by Ak-Shaw** [comment]
@all-contributors kindly add @divyanshrastogi51 for code doc ideas content

**Pull request merged**
