### PR TITLE
Connect Nodes at Same Level

### LINKED ISSUE #25: How to connect nodes at same level in a binary tree
**MicroByte Title:** BinaryTree_LevelOrderTraversal_Types

**Improvement Proposal:** 
- Add solution to connect nodes at same level as mentioned in Further Exploration Question 2
- Implement it in any language and add briefly documented code

**Benefits of proposed improvements:** 

- The learner will be able to find a solution to the Further Exploration section too

### PR DESCRIPTION
**Pull request by DivyaSaravanan**
## Closes #25 

**Checklist:**
- [ ] Added/updated activities for learners
- [ ]  Didn't give the solutions to the added/updated activities straight away
- [ ] Followed a LearnByDoing approach
- [x]  Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Comment by Ak-Shaw** [comment]
You should've made changes in the same PR, instead of closing and opening a new one. Kindly follow a proper workflow, it helps us to maintain contributions properly and also easier to guide you. This way potential contributors can look into PRs and learn from them. Nevertheless, also you need to edit the current PR description. Kindly remove the options which are not valid for your PR, like about adding images and use the checklist properly. 
Like this. 
- [x] example
You just need to put and 'x' inside the [].

**Comment by Ak-Shaw** [comment]
Also, your PR is currently under review.

**Review by Ak-Shaw — APPROVED** [review]
The code and Image is fine though.

**Comment by Ak-Shaw** [comment]
Thank you, I see you've got it. Wait till we get more approvals and your changes shall be merged.

**Comment by DivyaSaravanan** [comment]
Thank you @Ak-Shaw

**Review by sudhanshutiwari264 — APPROVED** [review]
Great work @DivyaSaravanan 🎉🎉
Keep contributing !

**Comment by archithdwij** [comment]
Great Work! @DivyaSaravanan . Kindly follow the workflow as mentioned by @Ak-Shaw in the upcoming contributions. Cheers!

**Pull request merged**
