### PR TITLE
[C++] Data Structures

### LINKED ISSUE #64: [Learners]Add your favourite data structures in your favourite langauage
**MicroByte Title:** Data Structured

**Improvement Proposal:** Add your favourite data structure to the [collection](https://github.com/TheShubham-K/DSA/tree/main/Getting%20Started%20with%20DSA/src) in ur favourite programming language

**Benefits of proposed improvements:** You enhance the collection and there by learn something new in DSA and add on a great help and scope extension of learning for learners.

P.S. : This is an open PR at all times. Feel free to contribute at ur own convenience

### PR DESCRIPTION
**Pull request by TheShubham-K**
## Closes #64 

Updated a microbyte by adding some famous data structures in C++ language

### Checklist: 
- [x] Clean and well documented code (if source code files are involved)
- [x] Extebded the collection of DS

### CODE REVIEW

**Comment by sudhanshutiwari264** [comment]
@TheShubham-K 
## So, The workflow is,

- First, you need to create an issue
- than Start working on byte
- Assigning happens in between
- Then PRs come in for review

>  Change your pr description and create an issue!
>  issue example: [tap here for issue template](https://github.com/Crio-Bytes/Miscellaneous/issues/33)

#### And Also follow the format for PR description as given in the template: [Tap here for template](https://github.com/Crio-Bytes/Miscellaneous/issues/33) 

### Look we are strict with the workflow and quality of bytes!
#### You look experienced by your GitHub profile, So we can expect good work from your side!

#  So, change your pr description as soon as possible and raise an issue also!
**You don't need to close this pr!**
**For any kind of assistance, we are always here for you!**
# Waiting for your contribution!🎉

**Comment by TheShubham-K** [comment]
okay

**Comment by Ayush7-BIT** [comment]
Hey we have to add solutions and questions for data structures in C++?

**Comment by Kevinpaulose05** [comment]
@all-contributors kindly add @TheShubham-K  for:

- [x] code
- [x] content

**Pull request merged**
