### PR TITLE
Update README.md

### LINKED ISSUE #57: Methods to transform an array in Javascript
**MicroByte Title:** Array in Javascript

**Improvement Proposal:** Add methods that transform and reorder an array and also add relevant problems.

**Benefits of proposed improvements:** These methods are necessary to solve frequently appearing problems related to arrays in Javascript.

### PR DESCRIPTION
**Pull request by Sreejan-22**
## Closes #57 
- Updated activities for learners
- Didn't give the solutions to the updated activities straight away
- Followed a LearnByDoing approach
- Added Todos and Micro-Challenge on the activity

### CODE REVIEW

**Review by Kevinpaulose05 — APPROVED** [review]

**Review by Ak-Shaw — APPROVED** [review]
@Sreejan-22 Well done! :100: You've improved the content from it's initial state. Thank you for your generous contribution! :heart_decoration: 

Let's see what the other reviewers have to say about it.

Keep contributing! :rocket:

**Comment by Ak-Shaw** [comment]
Well it seems that we can merge this PR, since we have two approvals! :rocket:

**Review by amoghrajesh — APPROVED** [review]
Hey @Sreejan-22!
Thanks for your contribution 👍🏽

**Comment by Kevinpaulose05** [comment]
Two things: 
1. U have used arrow function in map. Give a brief mention of it there
2. Change the stackoverflow link to a link with a suitable name

**Comment by Ak-Shaw** [comment]
@Sreejan-22 Since we've already merged this PR, kindly create a second one with these quick changes and we'll get it reviewed ASAP!

**Comment by Sreejan-22** [comment]
Okay

**Comment by Sreejan-22** [comment]
Done with the changes

**Pull request merged**
