### PR TITLE
First micro crio byte

### PR DESCRIPTION
**Pull request by Kevinpaulose05**
A getting started micro crio byte for DSA useful for competitive programming, interview preparation or programming in general!

### CODE REVIEW

**Comment by Kevinpaulose05** [comment]
Pls check if fine. Else do share

**Review by Ak-Shaw — APPROVED** [review]
LGTM! :rocket: 
Just one thing though, the branch name should be like `name/feature`. I'll add further details in the **CONTRIBUTING.md**. Kindly keep that in mind. It helps in maintaining a proper _workflow_.

**Review by amoghrajesh — APPROVED** [review]
Well done @Kevinpaulose05

**Comment by Ak-Shaw** [comment]
@all-contributors kindly add @Kevinpaulose05 for:

- code
- doc
- ideas
- content
- review
- eventOraganizing

**Comment by Ak-Shaw** [comment]
@all-contributors add @Kevinpaulose05 for eventOrganizing

**Comment by Ak-Shaw** [comment]
@all-contributors kindly add @amoghrajesh for review and eventOrganizing

**Pull request merged**
